<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { TaskPageLayout } from '@opsfactor/front-shell';
import { OfxPageHeader } from '@opsfactor/front-shell';
import { OfxDataTable } from '@opsfactor/front-shell';
import { OfxTableToolbar } from '@opsfactor/front-shell';
import { OfxTableCellText } from '@opsfactor/front-shell';
import { OfxSectionCard } from '@opsfactor/front-shell';
import { OfxEmptyState } from '@opsfactor/front-shell';
import { OfxLoadingState } from '@opsfactor/front-shell';
import { OfxConfirmDialog } from '@opsfactor/front-shell';
import type { OfxExportFormat } from '@opsfactor/front-shell';
import type { OfxTableColumn } from '@opsfactor/front-shell';
import type { SupplyPlanHistoryDto } from './supply-plans-history.types';

interface SupplyPlanHistoryRow extends Record<string, unknown>, SupplyPlanHistoryDto {
  rowKey: string;
  demandPlanIdDisplay?: number;
  demandPlanDescriptionDisplay?: string;
}

interface PlanHistoryNotification {
  tone: 'error' | 'success';
  title: string;
  description: string;
}

interface PlanHistoryNotifications {
  push: (notification: PlanHistoryNotification) => void;
}

const props = defineProps<{
  fetchSupplyPlanHistory: () => Promise<SupplyPlanHistoryDto[]>;
  deleteSupplyPlans: (plans: SupplyPlanHistoryDto[]) => Promise<string>;
  notifications: PlanHistoryNotifications;
}>();

const notifications = props.notifications;
const tableRef = ref<InstanceType<typeof OfxDataTable> | null>(null);

const exportFormat = ref<OfxExportFormat>('xlsx');
const isLoading = ref(true);
const isDeleting = ref(false);
const loadError = ref<string | null>(null);
const confirmDeleteOpen = ref(false);

const plans = ref<SupplyPlanHistoryDto[]>([]);
const selectedPlans = ref<SupplyPlanHistoryRow[]>([]);

const columns: OfxTableColumn[] = [
  { field: 'supplyPlanId', header: 'Supply Plan Id', width: '10%', dataType: 'number-0' },
  { field: 'description', header: 'Description', width: '16%', dataType: 'text' },
  { field: 'bucketSize', header: 'Time Bucket', width: '8%', dataType: 'text' },
  { field: 'beginsOn', header: 'Reference Period', width: '10%', dataType: 'date' },
  { field: 'generatedBy', header: 'Generated By', width: '12%', dataType: 'text' },
  { field: 'timeOfExecution', header: 'Generated On', width: '12%', dataType: 'datetime' },
  { field: 'supplyNetworkVersionId', header: 'Supply Network Version Id', width: '12%', dataType: 'text' },
  { field: 'executionProfileId', header: 'Execution Profile Id', width: '12%', dataType: 'text' },
  { field: 'demandPlanIdDisplay', header: 'Demand Plan Id', width: '8%', dataType: 'number-0' },
  { field: 'demandPlanDescriptionDisplay', header: 'Demand Plan Description', width: '16%', dataType: 'text' },
];

const rows = computed<SupplyPlanHistoryRow[]>(() =>
  plans.value.map((plan) => ({
    ...plan,
    rowKey: String(plan.supplyPlanId),
    demandPlanIdDisplay: plan.demandPlanDTO?.demandPlanId,
    demandPlanDescriptionDisplay: plan.demandPlanDTO?.description,
  })),
);

const selectedPlanIds = computed(() => selectedPlans.value.map((plan) => plan.supplyPlanId));
const selectedPlanListLabel = computed(() => selectedPlanIds.value.join(', '));

function formatError(error: unknown) {
  if (error instanceof Error && error.message) return error.message;
  return 'An unexpected error interrupted the supply-plan workflow.';
}

function toDeletePayload(plan: SupplyPlanHistoryRow): SupplyPlanHistoryDto {
  return {
    supplyPlanId: plan.supplyPlanId,
    supplyNetworkVersionId: plan.supplyNetworkVersionId,
    executionProfileId: plan.executionProfileId,
    description: plan.description,
    bucketSize: plan.bucketSize,
    timeOfExecution: plan.timeOfExecution,
    beginsOn: plan.beginsOn,
    generatedBy: plan.generatedBy,
    demandPlanDTO: plan.demandPlanDTO,
  };
}

async function loadPlans(options: { silent?: boolean } = {}) {
  if (!options.silent) {
    isLoading.value = true;
  }

  loadError.value = null;

  try {
    plans.value = await props.fetchSupplyPlanHistory();
  } catch (error) {
    loadError.value = formatError(error);

    if (options.silent) {
      notifications.push({
        tone: 'error',
        title: 'Unable to refresh supply plans',
        description: loadError.value,
      });
    }
  } finally {
    isLoading.value = false;
  }
}

function handleSelectionChange(selection: Record<string, unknown>[]) {
  selectedPlans.value = selection as unknown as SupplyPlanHistoryRow[];
}

function clearSelection() {
  tableRef.value?.clearSelection();
  selectedPlans.value = [];
}

function handleExport() {
  tableRef.value?.exportData(exportFormat.value);
}

async function confirmDeleteSelection() {
  if (!selectedPlans.value.length) return;

  isDeleting.value = true;

  try {
    const payload = selectedPlans.value.map(toDeletePayload);
    const responseMessage = await props.deleteSupplyPlans(payload);

    confirmDeleteOpen.value = false;
    clearSelection();
    await loadPlans({ silent: true });

    const requestedIds = payload.map((plan) => plan.supplyPlanId);
    const remainingIds = new Set(plans.value.map((plan) => plan.supplyPlanId));
    const stillVisible = requestedIds.filter((id) => remainingIds.has(id));

    notifications.push({
      tone: 'success',
      title: 'Deletion submitted',
      description: stillVisible.length
        ? `${responseMessage} The selected plans may stay visible until the async task finishes.`
        : responseMessage,
    });
  } catch (error) {
    notifications.push({
      tone: 'error',
      title: 'Unable to delete supply plans',
      description: formatError(error),
    });
  } finally {
    isDeleting.value = false;
  }
}

onMounted(() => {
  loadPlans();
});
</script>

<template>
  <TaskPageLayout>
    <OfxPageHeader eyebrow="Supply Chain Planning" title="Supply Plans" />

    <div class="space-y-4">
      <OfxSectionCard>
        <div v-if="isLoading" class="space-y-4">
          <OfxLoadingState label="Loading supply plan versions" />
        </div>

        <div v-else-if="loadError && !rows.length" class="space-y-4">
          <OfxEmptyState title="Supply plans unavailable" :description="loadError">
            <button
              class="rounded-md border border-[color:var(--ofx-border)] px-4 py-2 text-sm text-[color:var(--ofx-text)] transition hover:bg-white/[0.04]"
              @click="loadPlans()"
            >
              Try again
            </button>
          </OfxEmptyState>
        </div>

        <div v-else class="space-y-4">
          <div
            v-if="loadError && rows.length"
            class="rounded-lg border border-[color:rgb(211_155_42_/_0.24)] bg-[color:rgb(211_155_42_/_0.1)] px-4 py-3 text-sm text-[color:var(--ofx-text-warning)]"
          >
            {{ loadError }}
          </div>

          <OfxTableToolbar
            :results-label="`${rows.length} supply plan${rows.length === 1 ? '' : 's'}`"
            :download-format="exportFormat"
            @update:download-format="exportFormat = $event"
            @download="handleExport"
          >
            <template #actions>
              <button
                class="rounded-md border border-[color:rgb(208_69_95_/_0.34)] bg-[color:rgb(208_69_95_/_0.12)] px-4 py-2 text-sm font-medium text-[color:var(--ofx-text-danger)] transition hover:bg-[color:rgb(208_69_95_/_0.18)] disabled:cursor-not-allowed disabled:opacity-50"
                :disabled="!selectedPlans.length || isDeleting"
                @click="confirmDeleteOpen = true"
              >
                {{ isDeleting ? 'Deleting...' : `Delete Selected Plans${selectedPlans.length ? ` (${selectedPlans.length})` : ''}` }}
              </button>
            </template>
          </OfxTableToolbar>

          <OfxDataTable
            ref="tableRef"
            :rows="rows"
            :columns="columns"
            row-key="rowKey"
            :dense="true"
            :pagination="true"
            :page-size="10"
            :auto-page-size="false"
            :page-size-options="false"
            export-base-name="supply-plans-history"
            selection-mode="multiple"
            :selection-checkboxes="true"
            @selection-change="handleSelectionChange"
          >
            <template #empty>
              <OfxEmptyState
                title="No supply plans found"
                description="No supply-plan versions are available yet."
              />
            </template>

            <template #cell-supplyPlanId="{ value }">
              <OfxTableCellText :value="String(value || '')" />
            </template>

            <template #cell-description="{ row }">
              <OfxTableCellText :value="String(row.description || '')" fallback="Unnamed supply plan" />
            </template>

            <template #cell-bucketSize="{ value }">
              <OfxTableCellText :value="String(value || '')" fallback="Not informed" />
            </template>

            <template #cell-generatedBy="{ value }">
              <OfxTableCellText :value="String(value || '')" fallback="System" />
            </template>

            <template #cell-supplyNetworkVersionId="{ value }">
              <OfxTableCellText :value="String(value || '')" fallback="Not informed" />
            </template>

            <template #cell-executionProfileId="{ value }">
              <OfxTableCellText :value="String(value || '')" fallback="Not informed" />
            </template>

            <template #cell-demandPlanDescriptionDisplay="{ value }">
              <OfxTableCellText :value="String(value || '')" fallback="No linked demand plan" />
            </template>
          </OfxDataTable>
        </div>
      </OfxSectionCard>
    </div>

    <OfxConfirmDialog
      :open="confirmDeleteOpen"
      title="Delete supply plans"
      confirm-tone="danger"
      :confirm-label="isDeleting ? 'Submitting...' : 'Delete selected plans'"
      cancel-label="Keep plans"
      @cancel="!isDeleting ? (confirmDeleteOpen = false) : undefined"
      @confirm="!isDeleting ? confirmDeleteSelection() : undefined"
    >
      <div class="space-y-4">
        <div class="rounded-lg border border-[color:rgb(211_155_42_/_0.24)] bg-[color:rgb(211_155_42_/_0.08)] px-4 py-3 text-sm text-[color:var(--ofx-text-warning)]">
          Supply-plan deletion runs in the background. A refresh may still show the same rows briefly while the task finishes.
        </div>

        <div class="rounded-lg border border-[color:rgb(208_69_95_/_0.24)] bg-[color:rgb(208_69_95_/_0.08)] px-4 py-3 text-sm text-[color:var(--ofx-text-danger)]">
          This operation is definitive. Deleted supply plans cannot be restored afterward.
        </div>

        <div class="rounded-lg border border-[color:var(--ofx-border)] bg-[color:var(--ofx-bg-subtle)] px-4 py-3">
          <div class="text-xs uppercase tracking-[0.14em] text-[color:var(--ofx-text-subtle)]">Selected ids</div>
          <div class="mt-2 text-sm font-medium text-[color:var(--ofx-text)]">
            {{ selectedPlanListLabel }}
          </div>
        </div>
      </div>
    </OfxConfirmDialog>
  </TaskPageLayout>
</template>
